; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]

[env:h743vitx]
platform = ststm32@19.5.0
board = nucleo_h743zi
framework = stm32cube
lib_deps =
    stm32duino/STM32duino LwIP
lib_compat_mode = off
lib_ldf_mode = chain+
extra_scripts =
    pre:scripts/generate_ap6256_assets.py
    pre:scripts/prepare_freertos_sources.py
    pre:scripts/prepare_radio_sources.py
    pre:scripts/prepare_lwip_port.py

build_flags =
    -Iinclude
    -Ithird_party/cyw43-driver/src
    -Ithird_party/btstack/src
    -Ithird_party/btstack/platform/embedded
    -Ithird_party/btstack/chipset/bcm
    -mcpu=cortex-m7
    -mthumb
    -mfpu=fpv5-d16
    -mfloat-abi=hard

board_build.mcu = stm32h743vit6
board_build.ldscript = STM32H743VITX_FLASH_lwip.ld

upload_protocol = jlink
debug_tool = jlink

upload_flags =
    -device
    STM32H743VI
    -if
    SWD
    -speed
    1000
    -autoconnect
    1

debug_speed = 1000
